POST http://localhost:3000/sections/add_section
Content-Type: application/json

{
    "name": "Goober",
    "jobs": []
}

###

GET http://localhost:3000/dump

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "opti21",
    "password": "SuperSecure!"
}